import type { Reclamo, Usuario } from './types'

export const RECLAMOS: Reclamo[] = [
  {
    id: 'GR-2026-00428',
    cliente: 'Laura Rodríguez Vargas',
    cedula: '1-1456-0892',
    telefono: '8812-4590',
    correo: 'laura.rodriguez@gmail.com',
    producto: 'Refrigeradora Samsung RT38',
    marca: 'Samsung',
    modelo: 'RT38K5000S8',
    serie: 'SN92K41058',
    sucursal: 'San José Centro',
    asesor: 'Carlos Méndez',
    tecnico: 'Diego Vargas',
    prioridad: 'Media',
    estado: 'En Taller',
    fechaRegistro: '10/08/2026',
    fechaActualizacion: '14/08/2026',
    motivo: 'No enfría',
    descripcion: 'El cliente indica que la refrigeradora dejó de enfriar hace 3 días. El compresor suena pero la temperatura no baja de 18°C.',
    garantiaVigente: true,
    garantiaVencimiento: '18/04/2027',
  },
  {
    id: 'GR-2026-00415',
    cliente: 'Mario Jiménez Soto',
    cedula: '2-0521-0847',
    telefono: '8634-1102',
    correo: 'mjimenez@hotmail.com',
    producto: 'Televisor LG OLED55',
    marca: 'LG',
    modelo: 'OLED55C2PSA',
    serie: 'LG8419KR2210',
    sucursal: 'Curridabat',
    asesor: 'Andrea Mora',
    tecnico: 'Luis Cascante',
    prioridad: 'Alta',
    estado: 'Reparado',
    fechaRegistro: '04/08/2026',
    fechaActualizacion: '13/08/2026',
    motivo: 'Pantalla con líneas horizontales',
    descripcion: 'La pantalla presenta líneas horizontales de color en el tercio inferior. El problema aparece al encender y persiste.',
    garantiaVigente: true,
    garantiaVencimiento: '02/09/2026',
  },
  {
    id: 'GR-2026-00402',
    cliente: 'Ana Calderón Mora',
    cedula: '3-0612-0549',
    telefono: '7025-3388',
    correo: 'ana.calderon@gmail.com',
    producto: 'Lavadora Whirlpool WA65',
    marca: 'Whirlpool',
    modelo: 'WA65BH',
    serie: 'WP20L34401CR',
    sucursal: 'Liberia',
    asesor: 'Carlos Méndez',
    tecnico: 'Andrés Fonseca',
    prioridad: 'Baja',
    estado: 'Entregado',
    fechaRegistro: '28/07/2026',
    fechaActualizacion: '11/08/2026',
    motivo: 'No centrifuga',
    descripcion: 'La lavadora completa el ciclo de lavado pero no realiza el centrifugado, dejando la ropa con exceso de agua.',
    garantiaVigente: true,
    garantiaVencimiento: '15/11/2026',
  },
  {
    id: 'GR-2026-00431',
    cliente: 'Roberto Castro Fallas',
    cedula: '1-0984-0337',
    telefono: '8841-7720',
    correo: 'rcastro@empresa.cr',
    producto: 'Microondas Panasonic NN-ST34',
    marca: 'Panasonic',
    modelo: 'NN-ST34HMRPH',
    serie: 'PN26A011842',
    sucursal: 'Heredia',
    asesor: 'Andrea Mora',
    tecnico: '',
    prioridad: 'Media',
    estado: 'Escalado',
    fechaRegistro: '12/08/2026',
    fechaActualizacion: '14/08/2026',
    motivo: 'Garantía vencida presentada',
    descripcion: 'Cliente indica que el microondas emite chispas al calentar. La garantía de fábrica está vencida, pero el cliente alega garantía de servicio técnico previo.',
    garantiaVigente: false,
    motivoEscalamiento: 'Garantía de fábrica vencida el 10/07/2026. Cliente solicita revisión por garantía de servicio técnico anterior (OR-2025-1822). Requiere aprobación de administración.',
  },
  {
    id: 'GR-2026-00441',
    cliente: 'Patricia Vega Solís',
    cedula: '4-0155-0812',
    telefono: '8509-2214',
    correo: 'pvega@gmail.com',
    producto: 'Aire Acondicionado Carrier 18000 BTU',
    marca: 'Carrier',
    modelo: 'CA-18HV-220',
    serie: 'CR-18HV-26891',
    sucursal: 'San José Centro',
    asesor: 'Carlos Méndez',
    tecnico: 'Diego Vargas',
    prioridad: 'Alta',
    estado: 'En Diagnóstico',
    fechaRegistro: '14/08/2026',
    fechaActualizacion: '15/08/2026',
    motivo: 'No enfría / ruido inusual',
    descripcion: 'El equipo enciende pero no genera frío. Adicionalmente emite un golpeteo rítmico cada 30 segundos.',
    garantiaVigente: true,
    garantiaVencimiento: '30/06/2028',
  },
  {
    id: 'GR-2026-00388',
    cliente: 'Javier Brenes Quesada',
    cedula: '1-0645-0771',
    telefono: '8312-6650',
    correo: 'jbrenes@gmail.com',
    producto: 'Secadora Mabe SME04N5MNEBB',
    marca: 'Mabe',
    modelo: 'SME04N5MNEBB',
    serie: 'MB19K4007',
    sucursal: 'Cartago',
    asesor: 'Daniela Ulate',
    tecnico: 'Luis Cascante',
    prioridad: 'Media',
    estado: 'Cerrado',
    fechaRegistro: '22/07/2026',
    fechaActualizacion: '08/08/2026',
    motivo: 'No calienta',
    descripcion: 'La secadora gira pero no genera calor. La ropa queda húmeda después de ciclo completo.',
    garantiaVigente: false,
    motivoEscalamiento: 'Garantía vencida. Cerrado sin garantía, cliente pagó servicio.',
  },
]

export const USUARIOS: Usuario[] = [
  {
    id: 'U001',
    nombre: 'Carlos Méndez Araya',
    correo: 'c.mendez@gollo.cr',
    sucursal: 'San José Centro',
    rol: 'asesor',
    estado: 'Activo',
    ultimoAcceso: '15/08/2026 08:32',
  },
  {
    id: 'U002',
    nombre: 'Andrea Mora Picado',
    correo: 'a.mora@gollo.cr',
    sucursal: 'Heredia',
    rol: 'asesor',
    estado: 'Activo',
    ultimoAcceso: '15/08/2026 07:55',
  },
  {
    id: 'U003',
    nombre: 'Diego Vargas Chacón',
    correo: 'd.vargas@gollo.cr',
    sucursal: 'San José Centro',
    rol: 'tecnico',
    estado: 'Activo',
    ultimoAcceso: '15/08/2026 09:10',
  },
  {
    id: 'U004',
    nombre: 'Luis Cascante Porras',
    correo: 'l.cascante@gollo.cr',
    sucursal: 'Curridabat',
    rol: 'tecnico',
    estado: 'Activo',
    ultimoAcceso: '14/08/2026 17:45',
  },
  {
    id: 'U005',
    nombre: 'Andrés Fonseca León',
    correo: 'a.fonseca@gollo.cr',
    sucursal: 'Liberia',
    rol: 'tecnico',
    estado: 'Activo',
    ultimoAcceso: '15/08/2026 08:01',
  },
  {
    id: 'U006',
    nombre: 'Mariana Solano Barrantes',
    correo: 'm.solano@gollo.cr',
    sucursal: 'San José Centro',
    rol: 'admin',
    estado: 'Activo',
    ultimoAcceso: '15/08/2026 09:00',
  },
  {
    id: 'U007',
    nombre: 'Daniela Ulate Rojas',
    correo: 'd.ulate@gollo.cr',
    sucursal: 'Cartago',
    rol: 'asesor',
    estado: 'Inactivo',
    ultimoAcceso: '30/07/2026 14:20',
  },
]

export const USUARIOS_ACTIVOS = {
  asesor: { nombre: 'Carlos Méndez', sucursal: 'San José Centro', id: 'U001' },
  tecnico: { nombre: 'Diego Vargas', sucursal: 'San José Centro', id: 'U003' },
  admin: { nombre: 'Mariana Solano', sucursal: 'San José Centro', id: 'U006' },
}

export const SUCURSALES = [
  'San José Centro',
  'Curridabat',
  'Heredia',
  'Liberia',
  'Cartago',
  'Alajuela',
  'Puntarenas',
]

export const TECNICOS = [
  'Diego Vargas',
  'Luis Cascante',
  'Andrés Fonseca',
]
